### ISSUE TITLE
Make User-Select: text and change button cursor

### ISSUE THREAD

**Issue by eorroe** [GoogleChrome/voice-memos#15]
Use

``` CSS
-webkit-user-select: text;
-moz-user-select: text;
-ms-user-select: text;
-o-user-select: text;
user-select: text;
```

and the cursor for the CANCEL & OKAY:
![image](https://cloud.githubusercontent.com/assets/6982605/11450039/6e9806b6-955b-11e5-8334-7e564e463e56.png)

Use:

``` CSS
cursor: pointer;
```

**I didn't feel like opening a pull request for something that small**

**Comment by paullewis** [comment]
I disabled it for VM because it was inadvertently causing selections. That said, if there's -- say -- an a11y issue with that I'll gladly reverse it.

Regarding the cursor choice, it's a button, and the default style for a button isn't to have a hand cursor. In this instance I didn't want to break with tradition.
